//all action type 
export const MOVIELOADING = "MOVIELOADING";
export const MOVIETHEATREDATA = "MOVIETHEATREDATA";
export const POPULARMOVIEDATA = "POPULARMOVIEDATA";
export const POPULARKIDMOVIEDATA = "POPULARKIDMOVIEDATA";
export const BESTDRAMAMOVIEDATA = "BESTDRAMAMOVIEDATA";
export const ALLMOVIEDETAILS = "ALLMOVIEDETAILS";
export const MOVIEERROR = "MOVIEERROR";
